# general site variables, accessed in templates like {{ site.variable_name }}
title: Burton DeWilde
tagline: "data, art, sustainability"
description: >-
  Burton DeWilde's personal/professional website.
baseurl: ""  # the subpath of your site, e.g. /blog
url: ""  # the base hostname & protocol for your site, e.g. http://example.com
email: burtdewilde@gmail.com
timezone: America/New_York
lang: "en"
rss: false

socials:
  - name: GitHub
    link: https://github.com/bdewilde
    icon: "fa-github"
  - name: Mastodon
    link: https://mstdn.social/@burton
    icon: "fa-mastodon"
    rel: "me"
  - name: LinkedIn
    link: https://www.linkedin.com/in/burtondewilde
    icon: "fa-linkedin"

header_pages:
- pages/about.md
- pages/posts.html

# Build settings
theme: minima
plugins:
  - jekyll-archives
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
