title: Burton DeWilde
tagline: "Data Science, Physics, and Zombies!"
description: "data scientist, data scientologist, former physicist, filmmaker"
baseurl: ""
url: ""
email: burtondewilde@gmail.com
twitter_username: bjdewilde
github_username:  bdewilde
timezone: America/New_York

markdown: kramdown
permalink: pretty

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false
  input: GFM

#lsi: true

paginate: 10
#paginate_path: "blog/:num"

pages_list:       
  About: '/about/'
  Archive: '/archive/'
  #Feed: '/atom.xml'

