# Site settings
title: Work In Progress
description: "This is my site description, as set in _config.yml"
baseurl: ""
url: "http://yourdomain.com"
email: burtondewilde@gmail.com
twitter_username: bjdewilde
github_username:  bdewilde
timezone: America/New_York

# kramdown:
#   input: GFM

markdown: rdiscount
rdiscount:
  extensions: [smart]

# Build settings
markdown: kramdown
permalink: pretty
