title: Burton DeWilde
tagline: "Data Science, Physics, and Zombies!"
description: "data scientist / physicist / filmmaker"
baseurl: ""
url: ""
email: burtondewilde@gmail.com
twitter_username: bjdewilde
github_username:  bdewilde
linkedin_link: http://www.linkedin.com/pub/burton-dewilde/51/b18/301/
timezone: America/New_York

markdown: kramdown
permalink: pretty
#excerpt_separator: <!--more-->

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false
  input: GFM

#lsi: true

paginate: 10
paginate_path: "blog/p:num"


