# site settings
# variables accessible via liquid objects via {{ site.title }}, {{ site.email }}, etc.
# reference: https://jekyllrb.com/docs/configuration/default/

locale: "en-US"
title: "Burton DeWilde"
name: "Burton DeWilde"
tagline: "Data Science, Physics, and Zombies!"
description: >-
  Burton DeWilde's personal / professional website.
# the base hostname & protocol for your site e.g. "https://bdewilde.github.io"
url: ""
# the subpath of your site, e.g. "/blog"
baseurl: ""
email: burtdewilde@gmail.com
twitter_username: bjdewilde
github_username:  bdewilde
linkedin_link: http://www.linkedin.com/pub/burton-dewilde/51/b18/301/
title_separator: "-"

# directory structure
source: "."  # required by GitHub Pages to be set to the top level of this repo
destination: "./_site"
# collections_dir: "."  # NOTE: setting this value seems to break the site, so leave it
layouts_dir: "_layouts"
includes_dir: "_includes"
data_dir: "_data"
# plugins_dir: "_plugins"
sass:
  sass_dir: "_sass"
collections:
  posts:
    output: true

# handling reading
safe: true  # required true by GitHub Pages
include: [".htaccess"]
# exclude directories / files from processing
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "gemfiles/"
  - "node_modules/"
  - "vendor/bundle/"
  - "vendor/cache/"
  - "vendor/gems/"
  - "vendor/ruby/"
  - ".sass-cache/"
  - ".jekyll-cache/"
keep_files: [".git", ".svn"]
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
strict_front_matter : false

# filtering content
show_drafts: false
limit_posts: 0
future: false
unpublished: false

# plugins
plugins:
  - jekyll-archives
  - jekyll-include-cache  # required by minimal-mistakes-jekyll theme

# conversion
markdown: "kramdown"
highlighter: "rouge"  # required "rouge" by GitHub Pages
lsi: false  # required false by GitHub Pages
excerpt_separator: "\n\n"  # <!--more-->
incremental: false  # required false by GitHub Pages

# outputting
permalink: "pretty"
paginate_path: "blog/p:num"  # /page:num
timezone: "America/Chicago"

# markdown processor
# reference: https://jekyllrb.com/docs/configuration/markdown/
kramdown:
  auto_ids: true
  entity_output: "as_char"
  toc_levels: 1..6
  smart_quotes: "lsquo,rsquo,ldquo,rdquo"
  input: "GFM"
  footnote_nr: 1
  math_engine: "mathjax"  # required "mathjax" by GitHub Pages
  syntax_highlighter: "rouge"  # required "rouge" by GitHub Pages
  enable_coderay: false

# required exactly like this by GitHub Pages
gist:
  noscript: false

# plugin settings
search: false  # true, false (default)
search_full_content: false  # true, false (default)
search_provider: # lunr (default), algolia, google
sitemap: true
paginate: 5
feed:
  path: "/feed.xml"

# theme settings
# theme: minima  # minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.20.2"
# "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
minimal_mistakes_skin: "contrast"

analytics:
  # false (default), "google", "google-gtag", "custom"
  provider: "google"
  google:
    tracking_id: "UA-53458117-1"
    anonymize_ip: false

author:
  name: "Burton DeWilde"
  avatar: "/assets/images/about-pic.jpg"
  # bio: "My awesome biography constrained to a sentence or two goes here."
  location : "Chicago, IL"

comments:
  provider: "disqus"
  disqus:
    shortname: "bdewilde"
  staticman:
    branch: "master"
    endpoint: "https://burtbot-staticman.herokuapp.com/v3/entry/github/bdewilde/bdewilde.github.io"
    moderation: true
  utterances:
    theme: "github-light"
    issue_term: "pathname"

masthead:
  logo:  # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
  title:  # overrides the website title displayed in the masthead; use " " for no title
  subtitle:  # site tagline that appears below site title in masthead

footer:
  links:
    - label: "Email"
      icon: "fas fa-envelope-square fa-fw fa-2x"
      url: "mailto:burtdewilde@gmail.com"
    - label: "Twitter"
      icon: "fab fa-twitter-square fa-fw fa-2x"
      url: "https://twitter.com/bjdewilde"
    - label: "GitHub"
      icon: "fab fa-github-square fa-fw fa-2x"
      url: "https://github.com/bdewilde"
    - label: "LinkedIn"
      icon: "fab fa-linkedin fa-fw fa-2x"
      url: "http://www.linkedin.com/pub/burton-dewilde/51/b18/301"
    - label: "RSS"
      icon: "fas fa-rss-square fa-fw fa-2x"


# reCaptcha configuration info: the exact same site key and *encrypted* secret that you used in staticman.yml
# I personally don't think the secret needs to be included in the generated site, but the staticman API bridge uses
# it to ensure the site configuration and bridge configuration match (but why not just compare the site key?)
reCaptcha:
  siteKey: "6LdHbs8ZAAAAAEGgH0cLQQAvyGPCoqFZkFtiNs6k"
  secret: "ay2Emj+oAqdXIpnsfX2fwDNmBw/p5ywBfPrOfGLvrz010uIbwV6BBlIvyrKP3wGniBKorMBZUJg/AuDn/pNBlIaz9MrbxFpvXr8cdqnQ+/Up6+YeiY05MsgERp74O97bb7mrOLGQbPEuAkOO71NxJQg5d9ELCVAsevlB/vQhF4j5pr6CKv4F1eWSJ+AEzSKYzC7rGegVmqnsMaUAlD4gLu+t3g20Kkca/jWyrcb68kX+NT180x2sqjIyzlMNta7H/WND1UyBGou2azQ0Sk0+aXNSLvN0vniC12ls+MiOy9lBQaMfS8Vtjp1Qb9p1U6u+a8JC9k/aI4CzFUqCTFpwpm0XqFO3xzQMh6eEThGoaImX9gzHwkGj+TT45XmsNeMZNw2xeiD5T+pllQ5ih5P+3xOn+bpDh03152uFAN4LRgmxmV6AjGkKCrCNHgzP05MdK6hFHW9hkIqAmV0oKoyQL4sQhBXu7t6wwK7rlThENNw13ckDbtAVqzARbgJGNuJJeK091eKYVyquqYJR9LxA8HP1GRPKvmS8DlWgPvXaAjCOrjf1SiamoS109ixbLfq2wvNY2Pp0M4wKj7RDW76XHh9KUs9KEe04phC3USM4WJgnL9Ggwa/YSBY5k0K6eB8Chmb19eHWwsYKEpFExwVa3D0JUMYG6ZF0yh0GphEy8YM="
