# Site settings
title: burton dewilde
description: "This is my site description, as set in _config.yml"
baseurl: ""
url: http://bdewilde.github.io
email: burtondewilde@gmail.com
twitter_username: bjdewilde
github_username:  bdewilde
timezone: America/New_York

# Build settings
markdown: kramdown
permalink: pretty

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false
  input: GFM

#lsi: true

#paginate: 10
#paginate_path: "blog/:num"
