# Site settings
# Variables accessible via liquid objects via {{ site.title }}, {{ site.email }}, etc.
locale: "en-US"
title: "Burton DeWilde"
tagline: "Data Science, Physics, and Zombies!"
description: >-
  Burton DeWilde's personal / professional website.
# the base hostname & protocol for your site e.g. "https://bdewilde.github.io"
url: ""
# the subpath of your site, e.g. "/blog"
baseurl: ""
email: burtdewilde@gmail.com
twitter_username: bjdewilde
github_username:  bdewilde
linkedin_link: http://www.linkedin.com/pub/burton-dewilde/51/b18/301/
timezone: America/Chicago

title_separator: "-"

# Build settings
# theme: minima
# theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.20.2"
# "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
minimal_mistakes_skin: "contrast"

plugins:
  - jekyll-archives
  - jekyll-include-cache  # required by minimal-mistakes-jekyll theme

markdown: kramdown
permalink: pretty
#excerpt_separator: <!--more-->

# GitHub Pages settings -- these can't be changed!
lsi: false
safe: true
# source: [top level of this repo]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  input: GFM

paginate: 10
paginate_path: "blog/p:num"

sitemap: true

analytics:
  # false (default), "google", "google-gtag", "custom"
  provider: "google"
  google:
    tracking_id: "UA-53458117-1"
    anonymize_ip: false

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
