# Site settings
title: burton dewilde
description: "This is my site description, as set in _config.yml"
baseurl: ""
url: "http://yourdomain.com"
email: burtondewilde@gmail.com
twitter_username: bjdewilde
github_username:  bdewilde
timezone: America/New_York

# Build settings
markdown: kramdown
permalink: pretty

kramdown:
  input: GFM

paginate: 10
paginate_path: "blog/:num"
